// app/layout.tsx
import { GlobalProvider } from '@/context/GlobalContext'; // 경로를 맞게 설정
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <GlobalProvider>
            {children}
        </GlobalProvider>
        </body>
        </html>
    );
}